# .github/workflows/child.yml
name: Child Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  run-child:
    runs-on: ubuntu-latest
    steps:
      - name: Print the name
        run: echo "Hello, ${{ inputs.name }}"
