name: Target Workflow

on:
  repository_dispatch:
    types: [custom-trigger]

jobs:
  run-on-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "🎯 Triggered by another workflow!"
