name: Trigger Workflow

on:
  workflow_dispatch:  # இதுல நீங்க manually trigger பண்ணலாம் GitHub UI-ல இருந்து

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another workflow
        run: |
          curl -X POST https://api.github.com/repos/<OWNER>/<REPO>/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type":"custom-trigger"}'
